### ISSUE TITLE
new pypi release

### ISSUE THREAD

**Issue by theskumar** [nanvel/django-nicedit#6]
Hey @nanvel wondering if we can a new release on pypi after #5 is merged. 

Thanks for an awesome lib! :)

**Comment by nanvel** [comment]
Pls try this one:
https://pypi.python.org/pypi/django-nicedit

`pip install django-nicedit==1.1`

It doesn't use South and works for me with Django 1.7/1.8.

**Comment by theskumar** [comment]
awesomee!! Thanks @nanvel for making this happen!  👍 💟💟💟

**Comment by theskumar** [comment]
```
$ pip install django-nicedit==1.1
Collecting django-nicedit==1.1       ⇡ ⇡
  Downloading django-nicedit-1.1.tar.gz
Collecting Django<1.8,>=1.7 (from django-nicedit==1.1)
  Downloading Django-1.7.11-py2.py3-none-any.whl (7.4MB)
```

This is causing Django to downgrade from 1.8.

**Comment by nanvel** [comment]
Pls check out `django-nicedit==1.1.1`

**Comment by theskumar** [comment]
Works great! Thanks!
